# Generated by Django 5.0.6 on 2024-09-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
